### ISSUE TITLE
EWC fisher matrix: Why not use all of the gradient values in model?

### ISSUE THREAD

**Issue by ahnjaewoo** [jasonwu0731/trade-dst#18]
While I tried to reproduce `EWC_train.py`, I found something weird at line #51 (https://github.com/jasonwu0731/trade-dst/blob/4ee53da157a359666b6263e0828b55ccfe527084/EWC_train.py#L51).

I think one should use all of the gradient values in models to construct fisher matrix (which is `model.loss_grad.backward()`) but the code isn't written as it.

**Comment by andreamad8** [comment]
Hi, 

what do you mean by all the gradients in the model? 

Andrea

**Comment by ahnjaewoo** [comment]
Hi,
I mean there are two types of loss in TRADE model (https://github.com/jasonwu0731/trade-dst/blob/4ee53da157a359666b6263e0828b55ccfe527084/models/TRADE.py#L103)

But the fisher matrix only contains `model.loss_ptr_to_bp` term, as I mentioned above.
What if I just use `model.loss_grad` term instead of `model.loss_ptr_to_bp`?

**Comment by andreamad8** [comment]
Hi, 

yah good point. To be honest, no particular reasons, at the time we implemented we use that loss because we believed was the more important one. But for sure the sum of the two losses can be used. It may also work better. 

Thanks for letting us know. 

Andrea

Ps. I read your ICLR paper on sequential dialogue, nice work 👍

**Comment by ahnjaewoo** [comment]
Also thanks for faster reply :)

Ps. Thanks for reading the paper 😆I also hope to see your PPLM paper presentation🙏🏻
